name: goambulance
description: Ambulance booking application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  #general dependencies
  shared_preferences: ^2.1.2
  flutter_native_splash: ^2.3.1
  connectivity_plus: ^4.0.1
  internet_connection_checker_plus: ^1.0.1
  speech_to_text: ^6.2.0
  flutter_tts: ^3.7.0
  eg_nid: ^0.0.1
  intl: ^0.18.1
  #image: ^4.0.17
  permission_handler: ^10.3.0
  #translator: ^0.1.7
  background_sms: ^0.0.4
  async: ^2.11.0
  sensors_plus: ^3.0.2
  flutter_local_notifications: ^14.1.1


  #firebase dependencies
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_app_check: ^0.1.5
  firebase_crashlytics: ^3.3.3
  #firebase_database: ^10.2.3
  firebase_storage: ^11.2.4
  cloud_functions: ^4.3.3
  firebase_analytics: ^10.4.3
  firebase_messaging: ^14.6.4
  firebase_performance: ^0.9.2+3
  #firebase_dynamic_links: ^5.3.3

  #maps dependencies
  google_maps_flutter: ^2.3.1
  #google_maps_flutter_web: ^0.5.0+1
  custom_info_window: ^1.0.1
  geolocator: ^9.0.2
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  flutter_google_places_hoc081098: ^1.2.0
  geocoder2: ^1.4.0
  geoflutterfire2: ^2.3.15
  flutter_mapbox_navigation: ^0.1.8
  map_box_geocoder: ^0.0.12
  google_map_marker_animation: ^0.0.1

  #authentication dependencies
  google_sign_in: ^6.1.4
  #flutter_facebook_auth: ^6.0.0

  #UI dependencies
  custom_navigation_bar: ^0.8.2
  floating_draggable_widget: ^2.1.2
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  lottie: ^2.4.0
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  flutter_otp_text_field: ^1.1.1
  loading_animation_widget: ^1.2.0+4
  toggle_switch: ^2.1.0
  intl_phone_field: ^3.1.0
  animations: ^2.0.7
  logger: ^1.4.0
  flutter_inappwebview: ^6.0.0-beta.24+1
  #showcaseview: ^2.0.3
  flutter_staggered_animations: ^1.1.1
  #cupertino_icons: ^1.0.5
  shimmer: ^3.0.0
  flutter_web_frame: ^0.0.3
  line_icons: ^2.0.1
  flutter_zoom_drawer: ^3.1.1
  badges: ^3.1.1
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  flutter_phone_direct_caller: ^2.1.1
  syncfusion_flutter_datepicker: ^22.1.34
  image_picker: ^0.8.9
  cross_file_image: ^1.0.0
  custom_radio_grouped_button: ^2.2.0
  flutter_svg: ^2.0.7
  rolling_switch: ^0.0.2
  sliding_up_panel: ^2.0.0+1
  sweetsheet: ^0.4.0
  animated_custom_dropdown: 1.5.0
  top_snackbar_flutter: ^3.0.0+1
  pull_to_refresh: ^2.0.0
  photo_view: ^0.14.0
  swipeable_button_view: ^0.0.2
  circular_countdown_timer: ^0.2.3
  favorite_button: ^0.0.4

  #state management dependencies
  get: ^4.6.5
  path_provider: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#f7f6f1"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  #branding: assets/images/logo.png
  #branding_dark: assets/images/logo.png

  android_12:
    color: "#f7f6f1"
    color_dark: "#f7f6f1"
    image: assets/images/logo.png
    image_dark: assets/images/logo.png
    #branding: assets/images/logo.png
    #branding_dark: assets/images/logo.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/lottie_animations/
    - assets/gifs/
    - assets/files/
