name: goambulance
description: Ambulance booking application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  #general dependencies
  shared_preferences: ^2.1.1
  flutter_native_splash: ^2.3.1
  connectivity_plus: ^4.0.1
  internet_connection_checker_plus: ^1.0.1
  speech_to_text: ^6.1.1
  #flutter_tts: ^3.7.0
  awesome_notifications: ^0.7.4+1
  eg_nid: ^0.0.1
  intl: ^0.18.1
  #image: ^4.0.17
  permission_handler: ^10.2.0
  #translator: ^0.1.7
  flutter_sms: ^2.3.3
  async: ^2.11.0


  #firebase dependencies
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_app_check: ^0.1.4+2
  firebase_crashlytics: ^3.3.2
  #firebase_database: ^10.2.2
  firebase_storage: ^11.2.2
  #cloud_functions: ^4.3.2
  firebase_analytics: ^10.4.2
  firebase_messaging: ^14.6.2
  firebase_performance: ^0.9.2+2

  #google maps dependencies
  google_maps_flutter: ^2.2.8
  #google_maps_flutter_web: ^0.5.0
  custom_info_window: ^1.0.1
  geolocator: ^9.0.2
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  flutter_google_places_hoc081098: ^1.2.0
  geocoder2: ^1.4.0
  geoflutterfire2: ^2.3.15

  #authentication dependencies
  google_sign_in: ^6.1.3
  flutter_facebook_auth: ^5.0.11

  #UI dependencies
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  lottie: ^2.4.0
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  flutter_otp_text_field: ^1.1.1
  loading_animation_widget: ^1.2.0+4
  toggle_switch: ^2.1.0
  intl_phone_field: ^3.1.0
  animations: ^2.0.7
  logger: ^1.3.0
  flutter_inappwebview: ^6.0.0-beta.23
  #showcaseview: ^2.0.3
  flutter_staggered_animations: ^1.1.1
  #cupertino_icons: ^1.0.5
  shimmer: ^3.0.0
  flutter_web_frame: ^0.0.3
  persistent_bottom_nav_bar: ^5.0.2
  line_icons: ^2.0.1
  flutter_zoom_drawer: ^3.0.4+1
  flutter_platform_widgets: ^3.3.5
  badges: ^3.1.1
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  flutter_phone_direct_caller: ^2.1.1
  syncfusion_flutter_datepicker: ^21.2.8
  image_picker: ^0.8.7+5
  cross_file_image: ^1.0.0
  custom_radio_grouped_button: ^2.2.0
  flutter_svg: ^2.0.6
  rolling_switch: ^0.0.2
  sliding_up_panel: ^2.0.0+1
  sweetsheet: ^0.4.0
  animated_custom_dropdown: 1.5.0
  top_snackbar_flutter: ^3.0.0+1
  pull_to_refresh: ^2.0.0
  photo_view: ^0.14.0
  swipeable_button_view: ^0.0.2

  #state management dependencies
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#f7f6f1"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  #branding: assets/images/logo.png
  #branding_dark: assets/images/logo.png

  android_12:
    color: "#f7f6f1"
    color_dark: "#f7f6f1"
    image: assets/images/logo.png
    image_dark: assets/images/logo.png
    #branding: assets/images/logo.png
    #branding_dark: assets/images/logo.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/lottie_animations/
    - assets/gifs/
    - assets/files/
