name: goambulance
description: Ambulance booking application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #general dependencies
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.16
  connectivity_plus: ^3.0.2
  internet_connection_checker_plus: ^1.0.1
  awesome_notifications: ^0.7.4+1
  intl_phone_field: ^3.1.0
  qr_code_scanner: ^1.0.1

  #firebase dependencies
  firebase_core: ^2.3.0
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  firebase_app_check: ^0.1.1+7
  firebase_crashlytics: ^3.0.8
  firebase_database: ^10.0.8
  firebase_storage: ^11.0.9
  cloud_functions: ^4.0.6
  firebase_analytics: ^10.0.8
  firebase_messaging: ^14.1.4

  #google maps dependencies
  google_maps_flutter: ^2.2.2
  google_maps_flutter_web: ^0.4.0+3
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  geoflutterfire2: ^2.3.14

  #authentication dependencies
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.7

  #UI dependencies
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  lottie: ^2.1.0
  flutter_web_frame: ^0.0.3
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_otp_text_field: ^1.1.0+2
  loading_animation_widget: ^1.2.0+3

  #state management dependencies
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#f7f6f1"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  #branding: assets/images/logo.png
  #branding_dark: assets/images/logo.png

  android_12:
    color: "#f7f6f1"
    color_dark: "#f7f6f1"
    image: assets/images/logo.png
    image_dark: assets/images/logo.png
    #branding: assets/images/logo.png
    #branding_dark: assets/images/logo.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/lottie_animations/
    - assets/Gifs/
