// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkOoC0YCS7D3puztY3IB3m07MjDeSagw',
    appId: '1:996996980213:web:bd49d528ddc9e13fccd4bc',
    messagingSenderId: '996996980213',
    projectId: 'ambulancebookingproject',
    authDomain: 'ambulancebookingproject.firebaseapp.com',
    databaseURL: 'https://ambulancebookingproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ambulancebookingproject.appspot.com',
    measurementId: 'G-NVVTM3NBB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-fxxPyiLrpS3NexPCz9NijtQNAhk5VQ',
    appId: '1:996996980213:android:98ccd200e5bcad93ccd4bc',
    messagingSenderId: '996996980213',
    projectId: 'ambulancebookingproject',
    databaseURL: 'https://ambulancebookingproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ambulancebookingproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ5591rEa718a0_Ffi7uylBeGQ3k93Fvc',
    appId: '1:996996980213:ios:9207b1d25ddffd64ccd4bc',
    messagingSenderId: '996996980213',
    projectId: 'ambulancebookingproject',
    databaseURL: 'https://ambulancebookingproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ambulancebookingproject.appspot.com',
    iosClientId: '996996980213-8172m7d35r17qd730cjk6skirr4alsrf.apps.googleusercontent.com',
    iosBundleId: 'com.goambulance.goambulance',
  );
}
